name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Check
        run: pnpm run check

      - name: Build
        run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: 'dist/_worker.js'
